name: CI

on: [push, pull_request]

jobs:
  service-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: service

    steps:
      - uses: actions/checkout@v2
      - name: Cache bazel
        uses: actions/cache@v2
        env:
          cache-name: bazel-cache
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
          key: ${{ runner.os }}-${{ env.cache-name }}
      - name: Build
        run: bazel build //...
      - name: Test
        run: bazel test --test_output=all //...
